default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: kummerkasten_development

test:
  <<: *default
  database: kummerkasten_test
production:
  <<: *default
  database: kummerkasten_production
